/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaozeze_appdiffupdate_DiffPatchUtils */

#ifndef _Included_com_xiaozeze_appdiffupdate_DiffPatchUtils
#define _Included_com_xiaozeze_appdiffupdate_DiffPatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaozeze_appdiffupdate_DiffPatchUtils
 * Method:    genDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xiaozeze_appdiffupdate_DiffPatchUtils_genDiff
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_xiaozeze_appdiffupdate_DiffPatchUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xiaozeze_appdiffupdate_DiffPatchUtils_patch
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
